name: Clean up packages
on:
  workflow_dispatch:
jobs:
  clean:
    strategy:
      matrix:
        package:
          - annotation-tool
          - annotation-tool-frontend
          - annotation-tool-karaf-feature
          - annotation-tool-frontend-delivery
          - annotation-tool-backend
          - annotation-tool-api
          - annotation-tool-impl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v1
        with:
          package-name: org.opencast.annotate.${{ matrix.package }}
          num-old-versions-to-delete: 999
